/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package irrgarten.UI;

import irrgarten.Directions;
import irrgarten.GameState;

/**
 *
 * @author aloncraftmc
 */
public class GameFrame extends javax.swing.JFrame implements UI {
    
    private Cursors cursors;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GameFrame.class.getName());

    /**
     * Creates new form GameFrame
     */
    public GameFrame() {
        initComponents();
        this.cursors = new Cursors(this, true);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        labyrinthText = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        monstersText = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        playersText = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        logText = new javax.swing.JTextArea();
        currentPlayerTextField = new javax.swing.JTextField();
        winnerTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labyrinthText.setColumns(50);
        labyrinthText.setFont(new java.awt.Font("Liberation Mono", 0, 48)); // NOI18N
        labyrinthText.setRows(5);
        jScrollPane1.setViewportView(labyrinthText);

        monstersText.setColumns(20);
        monstersText.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        monstersText.setRows(5);
        jScrollPane2.setViewportView(monstersText);

        playersText.setColumns(20);
        playersText.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        playersText.setRows(5);
        jScrollPane3.setViewportView(playersText);

        logText.setColumns(20);
        logText.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        logText.setRows(5);
        jScrollPane4.setViewportView(logText);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 876, Short.MAX_VALUE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(currentPlayerTextField)
                        .addGap(18, 18, 18)
                        .addComponent(winnerTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane3)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 691, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 636, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane4)
                    .addComponent(currentPlayerTextField)
                    .addComponent(winnerTextField))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void showGame(GameState gameState){
        
        labyrinthText.setText(gameState.getLabyrinth());
        playersText.setText(gameState.getPlayers());
        monstersText.setText(gameState.getMonsters());
        logText.setText(gameState.getLog());
        
        currentPlayerTextField.setText("Player #" + gameState.getCurrentPlayer());
        winnerTextField.setText((gameState.isWinner() ? "WINNER: " + gameState.getCurrentPlayer() : ""));
        
        repaint();
        
    }
    
    public Directions nextMove(){
        return this.cursors.getDirection();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField currentPlayerTextField;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea labyrinthText;
    private javax.swing.JTextArea logText;
    private javax.swing.JTextArea monstersText;
    private javax.swing.JTextArea playersText;
    private javax.swing.JTextField winnerTextField;
    // End of variables declaration//GEN-END:variables
}
